services:
  - type: web
    name: constructrs-client
    env: static
    buildCommand: npm install --include=optional && npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
