services:
  - type: web
    name: constructrs-server
    env: node
    buildCommand: npm ci --include=optional && node verify-deps.js
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
